# Generated by Django 2.0.6 on 2018-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_id', models.IntegerField()),
                ('make_desc', models.CharField(max_length=128)),
                ('model_id', models.IntegerField()),
                ('model_desc', models.CharField(max_length=128)),
                ('variant_id', models.IntegerField()),
                ('variant_desc', models.CharField(max_length=128)),
                ('motor_flag', models.CharField(max_length=128)),
                ('fuel_type_id', models.IntegerField()),
                ('fuel_type_desc', models.CharField(max_length=128)),
                ('seating_capacity', models.IntegerField()),
                ('vehicle_image', models.CharField(max_length=128)),
                ('search_string', models.CharField(db_index=True, max_length=128)),
                ('search_count', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
