# Generated by Django 2.0.6 on 2018-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_search_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='search_string',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
